% -------------------------------------------------------------------
%  Generated by MATLAB on 16-May-2026 10:29:07
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
                                                   

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

frequencyDeviation = 50;

variance = 0.01;

